pipeline {
    agent any

    environment {
        DOCKERHUB_CREDENTIALS = credentials('dockerhub')
        REMOTE_HOST = '100.0.0.2'
        REMOTE_USER = 'vagrant'
        REMOTE_PASSWORD = 'vagrant'
    }

    tools {
        maven 'maven_3_5_0'
    }

    stages {
        stage('Build Maven') {
            steps {
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sami1895/devopssite.git']]])
                sh 'mvn -v'
            }
        }    
        stage('Docker Login') {
            steps {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }    
        stage('Build & push Dockerfile') {
            steps {
                sh """
                cd comingsoon/
                ansible-playbook playbook.yml
                """
            }
        }
        // Define 'remote' outside any stage to make it accessible across stages
        def remote = [
            name: 'k8s-master',
            host: env.REMOTE_HOST,
            user: env.REMOTE_USER,
            password: env.REMOTE_PASSWORD,
            allowAnyHosts: true
        ]

        stage("SSH Into k8s Server") {
            steps {
                // No need for defining 'remote' again here
            }
        }

        stage('Put-deployment.yml onto k8smaster') {
            steps {
                script {
                    sshPut remote: remote, from: 'deployment.yaml', into: '.'
                }
            }
        }
    }      
}	
