pipeline {
    agent any

    environment {
		DOCKERHUB_CREDENTIALS=credentials('dockerhub')
    }

    tools{
        maven 'maven_3_5_0'
    }
    stages {
        stage('Build Maven'){
            steps{
                checkout([$class: 'GitSCM', branches: [[name: '*/master']], extensions: [], userRemoteConfigs: [[url: 'https://github.com/sami1895/devopssite.git']]])
                sh 'mvn -v'
            }
        }    
        stage('Docker Login') {
            steps {
              sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }
        }    
        stage('Build & push Dockerfile') {
            steps {
              sh """
              cd comingsoon/
              ansible-playbook playbook.yml
              """
            }
        }
        stage("SSH Into k8s Server") {
        def remote = [:]
        remote.name = 'k8s-master'
        remote.host = '100.0.0.2'
        remote.user = 'vagrant'
        remote.password = 'vagrant'
        remote.allowAnyHosts = true
} 
	
    }	      
}	    
    
