node 

        stage('Docker Login') {
                sh 'echo $DOCKERHUB_CREDENTIALS_PSW | docker login -u $DOCKERHUB_CREDENTIALS_USR --password-stdin'
            }   
        stage('Build & push Dockerfile') {
                sh """
                cd comingsoon/
                ansible-playbook playbook.yml
                """
            }
         stage("SSH Into k8s Server") {
        def remote = [:]
        remote.name = 'K8S master'
        remote.host = '192.168.50.3'
        remote.user = 'vagrant'
        remote.password = 'vagrant'
        remote.allowAnyHosts = true
             stage('Put-deployment.yml onto k8smaster') {
                  sshPut remote: remote, from: 'comingsoon/k8s/deployment.yaml', into: '.'    
             stage('Deploy devops site') {
                  sshCommand remote: remote, command: "kubectl apply -f deployment.yaml"
        }   
                }
            }
            
    }      
}	
